apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fdx-ai-backstage
  description: Backstage application for the f(dx) AI Backstage experience.
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: ai-enablement
  lifecycle: experimental
