import { makeStyles } from '@material-ui/core/styles';
import { fdxDesignTokens } from './theme';

export const useAiBackstageStyles = makeStyles(theme => ({
  page: {
    position: 'relative',
    padding: theme.spacing(4, 4, 7),
    display: 'grid',
    gap: theme.spacing(4.5),
    maxWidth: 1440,
    margin: '0 auto',
    [theme.breakpoints.down('sm')]: {
      padding: theme.spacing(3, 2, 5),
    },
  },
  hero: {
    display: 'grid',
    gap: theme.spacing(3),
    padding: theme.spacing(4.5),
    position: 'relative',
    overflow: 'hidden',
    borderRadius: 0,
    background: fdxDesignTokens.neutralSurfaceSoft,
    boxShadow: fdxDesignTokens.shadowHero,
    [theme.breakpoints.down('sm')]: {
      padding: theme.spacing(3),
    },
  },
  heroSplit: {
    position: 'relative',
    zIndex: 1,
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1.7fr) minmax(280px, 0.9fr)',
    gap: theme.spacing(3),
    alignItems: 'start',
    [theme.breakpoints.down('md')]: {
      gridTemplateColumns: '1fr',
    },
  },
  heroContent: {
    display: 'grid',
    gap: theme.spacing(2),
  },
  heroTitle: {
    fontSize: '2.25rem',
    lineHeight: 1.1,
    letterSpacing: '-0.03em',
    fontWeight: 800,
    color: fdxDesignTokens.gray900,
    [theme.breakpoints.down('sm')]: {
      fontSize: '1.8rem',
    },
  },
  heroPanel: {
    display: 'grid',
    gap: theme.spacing(1.5),
    padding: theme.spacing(2.5),
    alignSelf: 'stretch',
    background: fdxDesignTokens.brandGray,
    color: fdxDesignTokens.onDarkSecondary,
    borderRadius: 0,
    boxShadow: fdxDesignTokens.shadowDarkPanel,
  },
  heroPanelLabel: {
    fontSize: '0.72rem',
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: '0.14em',
    color: fdxDesignTokens.overlayWhite72,
  },
  heroPanelValue: {
    fontSize: '1.8rem',
    fontWeight: 800,
    lineHeight: 1,
    color: fdxDesignTokens.onDarkPrimary,
  },
  heroPanelList: {
    display: 'grid',
    gap: theme.spacing(1),
  },
  heroPanelItem: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: theme.spacing(2),
    paddingTop: theme.spacing(1),
    borderTop: `1px solid ${fdxDesignTokens.overlayWhite12}`,
    fontSize: '0.88rem',
    color: fdxDesignTokens.overlayWhite82,
    '& strong': {
      color: fdxDesignTokens.onDarkPrimary,
      fontWeight: 700,
    },
  },
  eyebrow: {
    fontSize: '0.74rem',
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: '0.12em',
    color: fdxDesignTokens.gray600,
  },
  lede: {
    maxWidth: 860,
    color: fdxDesignTokens.brandGray,
    fontSize: '1.12rem',
    lineHeight: 1.75,
  },
  bodyText: {
    color: fdxDesignTokens.brandGray,
    fontSize: '0.98rem',
    lineHeight: 1.7,
  },
  mutedText: {
    color: fdxDesignTokens.gray600,
    fontSize: '0.9rem',
    lineHeight: 1.65,
  },
  heroMetrics: {
    position: 'relative',
    zIndex: 1,
  },
  metricsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    gap: theme.spacing(2),
    [theme.breakpoints.down('md')]: {
      gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    },
    [theme.breakpoints.down('xs')]: {
      gridTemplateColumns: '1fr',
    },
  },
  metricCard: {
    padding: theme.spacing(2.5),
    display: 'grid',
    gap: theme.spacing(0.75),
    borderRadius: 0,
    background: fdxDesignTokens.neutralSurface,
    boxShadow: fdxDesignTokens.shadowRaised,
  },
  metricValue: {
    fontSize: '2.2rem',
    fontWeight: 800,
    color: fdxDesignTokens.gray900,
  },
  metricHelper: {
    color: fdxDesignTokens.gray700,
    fontSize: '0.95rem',
    lineHeight: 1.55,
  },
  section: {
    display: 'grid',
    gap: theme.spacing(2),
  },
  sectionHeader: {
    display: 'grid',
    gap: theme.spacing(1.2),
    maxWidth: 860,
  },
  sectionTitle: {
    fontSize: '1.95rem',
    lineHeight: 1.15,
    letterSpacing: '-0.03em',
    fontWeight: 700,
    color: fdxDesignTokens.brandGray,
    [theme.breakpoints.down('sm')]: {
      fontSize: '1.55rem',
    },
  },
  cardGrid3: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: theme.spacing(2),
    [theme.breakpoints.down('md')]: {
      gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    },
    [theme.breakpoints.down('sm')]: {
      gridTemplateColumns: '1fr',
    },
  },
  cardGrid4: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    gap: theme.spacing(2),
    [theme.breakpoints.down('md')]: {
      gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    },
    [theme.breakpoints.down('sm')]: {
      gridTemplateColumns: '1fr',
    },
  },
  card: {
    padding: theme.spacing(3),
    display: 'grid',
    gap: theme.spacing(1.35),
    minHeight: 210,
    borderRadius: 0,
    background: fdxDesignTokens.neutralSurface,
    boxShadow: fdxDesignTokens.shadowCard,
  },
  cardBody: {
    minHeight: 72,
  },
  cardBodyText: {
    color: fdxDesignTokens.brandGray,
    fontSize: '0.96rem',
    lineHeight: 1.68,
  },
  repoMeta: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: theme.spacing(1),
    color: fdxDesignTokens.gray700,
    fontSize: '0.9rem',
  },
  tags: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: theme.spacing(1),
  },
  tag: {
    padding: theme.spacing(0.5, 1),
    backgroundColor: fdxDesignTokens.gray100,
    borderRadius: 0,
    fontSize: '0.78rem',
    fontWeight: 700,
    color: fdxDesignTokens.gray700,
  },
  tableWrapper: {
    overflowX: 'auto',
  },
  codeBlock: {
    margin: 0,
    padding: theme.spacing(2),
    borderRadius: 0,
    backgroundColor: fdxDesignTokens.gray900,
    color: fdxDesignTokens.onCodeSurface,
    overflowX: 'auto',
    fontSize: '0.85rem',
    lineHeight: 1.6,
  },
  diagramSurface: {
    padding: theme.spacing(2),
    borderRadius: 0,
    backgroundColor: fdxDesignTokens.neutralSurface,
    minHeight: 180,
    overflowX: 'auto',
  },
  searchSurface: {
    display: 'grid',
    gap: theme.spacing(2),
    padding: theme.spacing(3),
    background: fdxDesignTokens.neutralSurface,
    boxShadow: fdxDesignTokens.shadowCard,
  },
  searchInput: {
    width: '100%',
    '& .MuiInputBase-root': {
      borderRadius: 0,
      background: fdxDesignTokens.neutralSurface,
    },
    '& .MuiOutlinedInput-notchedOutline': {
      borderColor: fdxDesignTokens.gray200,
    },
  },
  searchResults: {
    display: 'grid',
    gap: theme.spacing(1.5),
  },
  searchResultCard: {
    display: 'grid',
    gap: theme.spacing(0.8),
    padding: theme.spacing(2),
    background: fdxDesignTokens.neutralSurface,
    boxShadow: fdxDesignTokens.shadowSoft,
  },
  searchResultMeta: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: theme.spacing(1),
    color: fdxDesignTokens.gray600,
    fontSize: '0.82rem',
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    fontWeight: 700,
  },
  statusOverviewGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: theme.spacing(2),
    [theme.breakpoints.down('md')]: {
      gridTemplateColumns: '1fr',
    },
  },
  statusOverviewCard: {
    padding: theme.spacing(3),
    borderRadius: 0,
    display: 'grid',
    gap: theme.spacing(1.35),
    background: fdxDesignTokens.neutralSurface,
    boxShadow: fdxDesignTokens.shadowCard,
  },
  statusOverviewValue: {
    fontSize: '2.35rem',
    fontWeight: 800,
    lineHeight: 1,
  },
  agentGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: theme.spacing(2.25),
    [theme.breakpoints.down('md')]: {
      gridTemplateColumns: '1fr',
    },
  },
  agentCard: {
    position: 'relative',
    display: 'grid',
    gap: theme.spacing(1.5),
    padding: theme.spacing(3.2),
    borderRadius: 0,
    background: fdxDesignTokens.neutralSurface,
    boxShadow: fdxDesignTokens.shadowCardStrong,
    overflow: 'hidden',
  },
  agentCardHeader: {
    position: 'relative',
    zIndex: 1,
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: theme.spacing(2),
  },
  agentOwner: {
    fontSize: '0.74rem',
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: '0.12em',
    color: fdxDesignTokens.gray600,
  },
  agentName: {
    fontSize: '1.52rem',
    fontWeight: 800,
    lineHeight: 1.15,
    letterSpacing: '-0.03em',
    color: fdxDesignTokens.gray900,
  },
  agentDescription: {
    position: 'relative',
    zIndex: 1,
    color: fdxDesignTokens.brandGray,
    fontSize: '1rem',
    lineHeight: 1.72,
    minHeight: 90,
  },
  agentFooter: {
    position: 'relative',
    zIndex: 1,
    display: 'grid',
    gap: theme.spacing(1.1),
  },
  agentMetaRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: theme.spacing(1),
  },
  agentMetaPill: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: theme.spacing(0.75),
    padding: theme.spacing(0.75, 1.1),
    borderRadius: 0,
    background: fdxDesignTokens.gray100,
    color: fdxDesignTokens.brandGray,
    fontSize: '0.82rem',
    fontWeight: 700,
  },
}));
